---

- name: Create mongo log directory
  file: path={{ log_dir }} state=directory mode="u=rwx,g=rwx,o=rx"
  tags:
    - mongo
    - deploy

- name: Create mongoDB directory
  file: path={{ remote_mongodb_dir }} state=directory mode="u=rwx,g=xr,o=x" owner=mongodb group=mongodb
  tags:
    - mongo
    - deploy

- name: Stop mongoDB docker container
  tags:
    - mongo
    - deploy
    - just-restart
    - just-stop
  docker:
    name: "{{ mongo_name }}"
    image: "{{ mongo_image }}"
    state: stopped

- name: Start mongoDB using docker in detached mode
  tags:
    - mongo
    - deploy
    - just-restart
  docker:
    name: "{{ mongo_name }}"
    image: "{{ mongo_image }}"
    state: reloaded
    pull: missing
    ports:
    - "{{ mongo_url }}:{{ mongo_port }}:{{ mongo_db_port }}"
    volumes:
    - "{{ remote_mongodb_dir }}:/data/db"
    - "{{ log_dir }}:/var/log/mongodb"
