---

# Base packages

- apt: update_cache=yes

- name: Install pip
  apt: name=python-pip state=present
  tags:
    - base
    - provision

- name: Make sure pip upgraded
  command: easy_install -U pip
  tags:
      - base
      - provision

- name: Make sure curl in installed
  apt: name=curl state=present
  tags:
      - base
      - provision

- name: Make sure ufw in installed
  apt: name=ufw state=present
  tags:
      - base
      - provision

- name: Make sure locale is set properly
  copy: src="locale" dest="/etc/default" mode="u=r,g=r,o=r"
  tags:
      - base
      - provision
      - locale
