---

- name: Add Zabbix 2.4 repository
  apt_repository: repo="deb http://repo.zabbix.com/zabbix/2.4/ubuntu/ {{ zabbix_dist_name }} main" state=present
  tags:
      - zabbix
      - provision

- name: Add Zabbix 2.4 source repository
  apt_repository: repo="deb-src http://repo.zabbix.com/zabbix/2.4/ubuntu/ {{ zabbix_dist_name }} main" state=present
  tags:
      - zabbix
      - provision

- name: "Install gpg key for Zabbix"
  apt_key: id=79EA5ED4 url=http://repo.zabbix.com/zabbix-official-repo.key
  sudo: yes
  tags:
      - zabbix
      - provision

- apt: update_cache=yes
  tags:
      - zabbix
      - provision

- name: Install zabbix aggent
  apt: name=zabbix-agent state=present
  tags:
      - zabbix
      - provision
