---
# This playbook deploys the package jar to remote server.

- hosts: all
  sudo: yes
  roles:
    - base
    - docker
    - mongo
    - nginx
    - loadbalancer
    - logstash-fwd
    - zabbix
    - monit
